// Song/title list extracted from `newtz.txt` (library used for project names)
export const SONG_TITLES: string[] = [
  'BTS — ECLIPSE',
  'NCT 127 — Gravity Rush',
  'Stray Kids — Venomous',
  'TXT — Night Dive',
  'EXO — Wicked Bloom',
  'Ateez — Pirate Code',
  'Enhypen — Dark Paradigm',
  'Seventeen — Mirrorlight',
  'Monsta X — Voltage Line',
  'The Boyz — Echo Punch',
  'NCT Dream — Jellyknife',
  'WayV — Pulse Storm',
  'Treasure — Jet Fuel',
  'Pentagon — Arc Driver',
  'Shinee — Silver Neon',
  'iKON — Last Sinner',
  'Astro — Goodnight Fire',
  'SF9 — Burn It Waves',
  'Tempest — Cryonix',
  'BoyNextDoor — Speeding Youth',
  'EPEX — Thriller Boy',
  'Xdinary Heroes — Neo Riot',
  'EVNNE — Overdrive Me',
  '8TURN — Red Shell',
  'Xodiac — HyperKick',
  'ZEROBASEONE — Rainmaker',
  'RIIZE — Black Orbit',
  'ATBO — Jumpcut',
  'YOUNITE — Fire Switch',
  'TAN — Combat Kiss',
  'Kingdom — Spiral Crown',
  'Mirae — Neon Runner',
  'BLITZERS — Urban Jam',
  'Just B — Nightmotor',
  'TST — Lunar Path',
  'TRCNG — Code Star',
  'BAE173 — Zero Trick',
  'GreatGuys — IronRush',
  'LUMINOUS — Shadow Step',
  'WEi — Gravity Burn',
  'Blackpink — Venom Kiss',
  'Twice — Cherry Pulse',
  'Itzy — Cyber Idol',
  'Le Sserafim — Hot Scar',
  'IVE — Golden Veil',
  'NewJeans — Bubble Night',
  'Aespa — CryoQueen',
  '(G)I-DLE — Wild Crown',
  'Red Velvet — Sweet Mirage',
  'Fromis_9 — Lady Voltage',
  'Oh My Girl — Blue Cotton',
  'Apink — Soft Trigger',
  'Everglow — Neon Blade',
  'WJSN — Stardust Bloom',
  'Momoland — CandyFrame',
  'Purple Kiss — Siren Craft',
  'StayC — Midnight Ride',
  'woo!ah! — Pop Drill',
  'Rocket Punch — Laserbright',
  'Cherry Bullet — Pixel Riot',
  'BBGIRLS — Stardriver',
  'Billlie — Overlight',
  'NMIXX — FishEye',
  'Kep1er — Starzoom',
  'CLASS:y — Bloomshock',
  'CSR — Lightwish',
  'tripleS — Motion Error',
  'IRRIS — Moon Splice',
  'ARTMS — NightFlower',
  'ME:I — Pretty Danger',
  'LIMELIGHT — Vivid Rock',
  'Weeekly — Jump Daisy',
  'H1-KEY — Aftermatch',
  'Dreamcatcher — Phantom Echo',
  'EL7Z UP — Sugar Rushdown',
  'PIXY — Darklight Siren',
  'Lapillus — HyperPretty',
  'ILY:1 — Crystal Pop',
  'Queenz Eye — Silver Poison',
  'Catch The Young — Peach Motion',
  'KARD — Dual Edge',
  'KARD — Shadow Bite',
  'KARD — Love Reactor',
  'KARD — Hell&Honey',
  'BABYMONSTER — Chrome Tears',
  'BABYMONSTER — Blue Tiger',
  'BABYMONSTER — Synch Knife',
  'XG — Neon Pulse',
  'XG — Burn Inside',
  'Coed Crew Nova — Light/Noise',
  'Coed Crew Nova — Plastic Heart',
  'Kiss of Life — Gold Melt',
  'Kiss of Life — Route99',
  'TripleS LOVElution — Sharp Dream',
  'TripleS LOVElution — MoonCry',
  'EVNNE × Kep1er — Voltage Love',
  'NCT × Aespa — HyperBoost',
  'The Boyz × IVE — SweetCrusher',
  'TXT × Le Sserafim — VenomLace',
  'CSR × YOUNITE — Lavender Flash',
  'ITZY × Stray Kids — Wild Synchrony',
  'Purple Kiss × ONEUS — Cypher Rose',
  'VCHA × RIIZE — Street Bloom',
  'PIXY × Blitzers — Red Oracle',
  'CLASS:y × Tempest — DanceRush',
  'Rocket Punch × WEi — Orbit Sugar',
  'IRRIS × MIRAE — Cloud Crash',
  'Billlie × The Boyz — Bright Poison',
  'EXO × Aespa — Hypercode',
  'Dreamcatcher × TXT — Night Spell',
  'tripleS × ATBO — Zero Bloom',
  'IVE × ZEROBASEONE — Lightfall',
];

export default SONG_TITLES;
